name: golden_datasets
channels:
  - anaconda
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - gatk4=4.1.2.0
  - pigz=2.4
  - pip=20.0.2
  - synapseclient=2.2.0
  - which=2.21
  - pip:
      - gsutil==4.49
